export const UPDATE_FILTER = "[SHARED] UPDATE_FILTER";
export const RESET_ALL_FILTERS = "[SHARED] RESET_ALL_FILTERS";
export const RESET_POPERTY_FILTERS =
  "[SHARED] RESET_POPERTY_FILTERS";
export const UPDATE_NAVIGATION_PROPERTY_FILTER =
  "[SHARED] UPDATE_NAVIGATION_PROPERTY_FILTER";
export const UPDATE_FUNCTION_FILTER =
  "[SHARED] UPDATE_FUNCTION_FILTER";
export const UPDATE_MULTIPLE_FUNCTION_FILTERS =
  "[SHARED] UPDATE_MULTIPLE_FUNCTION_FILTERS";
export const OVERRIDE_STATE =
  "[SHARED] OVERRIDE_STATE";
