export const FILTER_UPDATE_FILTER = "[SHARED] FILTER_UPDATE_FILTER";
export const FILTER_RESET_ALL_FILTERS = "[SHARED] FILTER_RESET_ALL_FILTERS";
export const FILTER_RESET_POPERTY_FILTERS =
  "[SHARED] FILTER_RESET_POPERTY_FILTERS";
export const FILTER_UPDATE_NAVIGATION_PROPERTY_FILTER =
  "[SHARED] FILTER_UPDATE_NAVIGATION_PROPERTY_FILTER";
export const FILTER_UPDATE_FUNCTION_FILTER =
  "[SHARED] FILTER_UPDATE_FUNCTION_FILTER";
export const FILTER_UPDATE_MULTIPLE_FUNCTION_FILTERS =
  "[SHARED] FILTER_UPDATE_MULTIPLE_FUNCTION_FILTERS";
export const FILTER_OVERRIDE_FILTER_STATE =
  "[SHARED] FILTER_OVERRIDE_FILTER_STATE";
